// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBzjU-VFBojV4Zwc1SSI1QJgMzkJnvWQ',
    appId: '1:846112485316:web:be7b4822443c94bcce7e91',
    messagingSenderId: '846112485316',
    projectId: 'flutter-backend-808a3',
    authDomain: 'flutter-backend-808a3.firebaseapp.com',
    storageBucket: 'flutter-backend-808a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoEIosDxmjc4FuF6RElbskQVjr72eNvBE',
    appId: '1:846112485316:android:fe4ee06f5f07603ece7e91',
    messagingSenderId: '846112485316',
    projectId: 'flutter-backend-808a3',
    storageBucket: 'flutter-backend-808a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC4r0K8QQiP0BFRFjRrkkHyO-9ndvNqlQ',
    appId: '1:846112485316:ios:1ae1185fa04be392ce7e91',
    messagingSenderId: '846112485316',
    projectId: 'flutter-backend-808a3',
    storageBucket: 'flutter-backend-808a3.firebasestorage.app',
    iosClientId: '846112485316-gnpqob16gc3ieqhd7i83ijt2o03mufcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC4r0K8QQiP0BFRFjRrkkHyO-9ndvNqlQ',
    appId: '1:846112485316:ios:1ae1185fa04be392ce7e91',
    messagingSenderId: '846112485316',
    projectId: 'flutter-backend-808a3',
    storageBucket: 'flutter-backend-808a3.firebasestorage.app',
    iosClientId: '846112485316-gnpqob16gc3ieqhd7i83ijt2o03mufcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRBzjU-VFBojV4Zwc1SSI1QJgMzkJnvWQ',
    appId: '1:846112485316:web:d19b08ff87ad7bd5ce7e91',
    messagingSenderId: '846112485316',
    projectId: 'flutter-backend-808a3',
    authDomain: 'flutter-backend-808a3.firebaseapp.com',
    storageBucket: 'flutter-backend-808a3.firebasestorage.app',
  );
}
